version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./log/:/var/log/dnmp/:rw
    networks:
      - default


  php72:
    image: jingmian/php-fpm-max:7.2
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:ro
      - ${PHP72_LOG_DIR}:/var/log/php
    cap_add:
      - SYS_PTRACE
    networks:
      - default


  php56:
    image: jingmian/php-fpm-max:5.6
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:ro
      - ${PHP56_LOG_DIR}:/var/log/php
    cap_add:
      - SYS_PTRACE
    networks:
      - default


  php54:
    image: jingmian/php-fpm-max:5.4
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP54_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP54_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:ro
      - ${PHP54_LOG_DIR}:/var/log/php
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  php53:
    image: jingmian/php-fpm-max:5.3
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP53_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP53_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:ro
      - ${PHP53_LOG_DIR}:/var/log/php
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    image: redis:4.0
    networks:
      - default
    ports:
      - "6380:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - default
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "8081:80"
    networks:
      - default
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379



networks:
  default:
